# Generated by Django 3.2.6 on 2021-08-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('searchsubject', models.CharField(blank=True, db_column='searchSubject', max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.CharField(blank=True, max_length=100, null=True)),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('painter', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('publishdate', models.CharField(blank=True, db_column='publishDate', max_length=100, null=True)),
                ('intro', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('authorintro', models.CharField(blank=True, max_length=1000, null=True)),
                ('categorytop', models.CharField(blank=True, db_column='categoryTop', max_length=100, null=True)),
                ('categorymiddle', models.CharField(blank=True, db_column='categoryMiddle', max_length=100, null=True)),
                ('categorybottom', models.CharField(blank=True, db_column='categoryBottom', max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=100, null=True)),
                ('bid', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
    ]
